"""create relation between user an category

Revision ID: 82306f331fe5
Revises: 5b672cfe5cc1
Create Date: 2023-06-12 08:15:54.709593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82306f331fe5'
down_revision = '5b672cfe5cc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_category',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_column('user', 'subscribed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('subscribed', sa.VARCHAR(length=255), nullable=True))
    op.drop_table('user_category')
    # ### end Alembic commands ###
